# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e5345202433ca133491f3f117ceb4273"
name = "Timex Chat AI"
handle = "timex-chat-ai"
application_url = "https://agent.timex.com"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_read_orders,customer_read_store_credit_account_transactions,customer_read_store_credit_accounts,unauthenticated_read_product_listings"

[auth]
redirect_urls = [
  "https://agent.timex.com/auth/callback",
  "https://agent.timex.com/auth/shopify/callback",
  "https://agent.timex.com/api/auth/callback"
]

[pos]
embedded = false
